<?php

use CRM_OAuthLogin_ExtensionUtil as E;

return [
  'oauth_login_mode' => [
    'group' => 'oauth_login',
    'name' => 'oauth_login_mode',
    'type' => 'String',
    'default' => 'disabled',
    'html_type' => 'select',
    'title' => E::ts('OAuth Login Mode'),
    'description' => E::ts('disabled = password only; optional = password + SSO button; required = SSO only (password form hidden and the login page auto-redirects to the identity provider).'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_OAUTH_LOGIN_MODE',
    'options' => [
      'disabled' => E::ts('Disabled'),
      'optional' => E::ts('Optional'),
      'required' => E::ts('Required'),
    ],
  ],
  'oauth_login_provisioning_enabled' => [
    'group' => 'oauth_login',
    'name' => 'oauth_login_provisioning_enabled',
    'type' => 'Boolean',
    'default' => TRUE,
    'html_type' => 'checkbox',
    'title' => E::ts('Auto-provision Users'),
    'description' => E::ts('When enabled, an unknown OAuth identity results in a new CiviCRM User/Contact being created on first login.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_OAUTH_LOGIN_PROVISIONING_ENABLED',
  ],
  'oauth_login_contact_create_matcher' => [
    'group' => 'oauth_login',
    'name' => 'oauth_login_contact_create_matcher',
    'type' => 'String',
    'default' => '',
    'html_type' => 'select',
    'title' => E::ts('Contact Creation Mechanism'),
    'description' => E::ts('How to handle the contact creation upon login. Each user record in CiviCRM has a related contact record.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_required' => TRUE,
    'pseudoconstant' => [
      'callback' => 'CRM_OAuthLogin_Utils_PseudoConstants::contactCreateMatchers',
    ],
    'html_attributes' => [
      'class' => 'crm-select2 huge',
      'placeholder' => E::ts(' - Select one - ')
    ],
    'settings_pages' => ['oauth_login' => ['section' => 'contact_create']],
  ],
  'oauth_login_contact_update_matcher' => [
    'group' => 'oauth_login',
    'name' => 'oauth_login_contact_update_matcher',
    'type' => 'String',
    'default' => '',
    'html_type' => 'select',
    'title' => E::ts('Contact Update Mechanism'),
    'description' => E::ts('How to handle contact updates upon login. Each user record in CiviCRM has a related contact record.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_required' => FALSE,
    'pseudoconstant' => [
      'callback' => 'CRM_OAuthLogin_Utils_PseudoConstants::contactUpdateMatchers',
    ],
    'html_attributes' => [
      'class' => 'crm-select2 huge',
      'placeholder' => E::ts('Do not update')
    ],
    'settings_pages' => ['oauth_login' => ['section' => 'contact_update']],
  ],
  'oauth_login_username_claim' => [
    'group' => 'oauth_login',
    'name' => 'oauth_login_username_claim',
    'type' => 'String',
    'default' => 'username',
    'html_type' => 'text',
    'title' => E::ts('Username Claim'),
    'description' => E::ts('Name of the OAuth claim in the access token that carries the username.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_OAUTH_LOGIN_ATTR_USERNAME',
  ],
  'oauth_login_email_claim' => [
    'group' => 'oauth_login',
    'name' => 'oauth_login_email_claim',
    'type' => 'String',
    'default' => 'email',
    'html_type' => 'text',
    'title' => E::ts('E-mail claim'),
    'description' => E::ts('Name of the OAuth claim in the access token that carries the email address.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_OAUTH_LOGIN_ATTR_EMAIL',
  ],
  'oauth_login_default_roles' => [
    'group' => 'oauth_login',
    'name' => 'oauth_login_default_roles',
    'type' => 'String',
    'default' => 'staff',
    'html_type' => 'select',
    'title' => E::ts('Default Roles for Provisioned Users'),
    'description' => E::ts('Comma- or newline-separated CiviCRM Role names to assign when a user is first provisioned via OAuth. Applied only at provision time — subsequent logins do not touch these roles, so admins can adjust roles in CiviCRM and the changes stick.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_OAUTH_LOGIN_DEFAULT_ROLES',
    'pseudoconstant' => [
      'callback' => 'CRM_OAuthLogin_Utils_PseudoConstants::roles',
    ],
    'html_attributes' => [
      'class' => 'crm-select2 huge',
      'multiple' => 1,
      'placeholder' => E::ts('None'),
    ],
  ],
];