<?php

use CRM_OauthLogin_ExtensionUtil as E;

return [
  'oauth_login_mode' => [
    'group' => 'oauth_login',
    'name' => 'oauth_login_mode',
    'type' => 'String',
    'default' => 'disabled',
    'html_type' => 'select',
    'title' => E::ts('OAuth Login Mode'),
    'description' => E::ts('disabled = password only; optional = password + SSO button; required = SSO only (password form hidden and the login page auto-redirects to the identity provider).'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_OAUTH_LOGIN_MODE',
    'options' => [
      'disabled' => E::ts('Disabled'),
      'optional' => E::ts('Optional'),
      'required' => E::ts('Required'),
    ],
  ],
  'oauth_login_provisioning_enabled' => [
    'group' => 'oauth_login',
    'name' => 'oauth_login_provisioning_enabled',
    'type' => 'Boolean',
    'default' => TRUE,
    'html_type' => 'checkbox',
    'title' => E::ts('Auto-provision Users'),
    'description' => E::ts('When enabled, an unknown OAuth identity results in a new CiviCRM User/Contact being created on first login.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_OAUTH_LOGIN_PROVISIONING_ENABLED',
  ],
  'oauth_login_contact_matcher' => [
    'group' => 'oauth_login',
    'name' => 'oauth_login_contact_matcher',
    'type' => 'String',
    'default' => '',
    'html_type' => 'select',
    'title' => E::ts('Contcat Creation Mechanism'),
    'description' => E::ts('When Auto-provision is enabled this setting determines how linked contacts are created.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_OAUTH_LOGIN_CONTACT_MATCHER',
    'pseudoconstant' => [
      'callback' => 'CRM_OauthLogin_Utils_PseudoConstants::contactMatchers',
    ],
    'html_attributes' => [
      'class' => 'crm-select2',
    ],
  ],
  'oauth_login_attr_username' => [
    'group' => 'oauth_login',
    'name' => 'oauth_login_attr_username',
    'type' => 'String',
    'default' => 'username',
    'html_type' => 'text',
    'title' => E::ts('OAuth attribute: username'),
    'description' => E::ts('Name of the OAuth attribute that carries the username. Leave blank to skip username when provisioning / fall back to NameID.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_OAUTH_LOGIN_ATTR_USERNAME',
  ],
  'oauth_login_attr_email' => [
    'group' => 'oauth_login',
    'name' => 'oauth_login_attr_email',
    'type' => 'String',
    'default' => 'email',
    'html_type' => 'text',
    'title' => E::ts('OAuth attribute: email'),
    'description' => E::ts('Name of the OAuth attribute that carries the email address. Leave blank to fall back to NameID when match field is email.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_OAUTH_LOGIN_ATTR_EMAIL',
  ],
  'oauth_loginattr_first_name' => [
    'group' => 'oauth_login',
    'name' => 'oauth_login_attr_first_name',
    'type' => 'String',
    'default' => 'firstName',
    'html_type' => 'text',
    'title' => E::ts('OAuth attribute: first name'),
    'description' => E::ts('Leave blank to skip first name.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_OAUTH_LOGIN_ATTR_FIRST_NAME',
  ],
  'oauth_login_attr_last_name' => [
    'group' => 'oauth_login',
    'name' => 'oauth_login_attr_last_name',
    'type' => 'String',
    'default' => 'lastName',
    'html_type' => 'text',
    'title' => E::ts('OAuth attribute: last name'),
    'description' => E::ts('Leave blank to skip last name.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_OAUTH_LOGIN_ATTR_LAST_NAME',
  ],
  'oauth_login_default_roles' => [
    'group' => 'oauth_login',
    'name' => 'oauth_login_default_roles',
    'type' => 'String',
    'default' => 'staff',
    'html_type' => 'select',
    'title' => E::ts('Default Roles for Provisioned Users'),
    'description' => E::ts('Comma- or newline-separated CiviCRM Role names to assign when a user is first provisioned via OAuth. Applied only at provision time — subsequent logins do not touch these roles, so admins can adjust roles in CiviCRM and the changes stick.'),
    'is_domain' => 1,
    'is_contact' => 0,
    'is_env_loadable' => TRUE,
    'global_name' => 'CIVICRM_OAUTH_LOGIN_DEFAULT_ROLES',
    'pseudoconstant' => [
      'callback' => 'CRM_OauthLogin_Utils_PseudoConstants::roles',
    ],
    'html_attributes' => [
      'class' => 'crm-select2',
      'multiple' => 1,
    ],
  ],
];